version: '3.3'

services:

    nginx:
      build: ./nginx
      container_name: ex-vue
      ports:
        - 8080:80
      networks:
        - net
      volumes:
        - ./dist:/usr/share/nginx/html

networks:
  net:
